name: Deploy static site to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: static-site
          path: .

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: static-site

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_976C8A8E400942AC996A25E052AECD96 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6AC7DF6E5F014DD995B4A2F6CB6C47BB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0CE96A9D2B504A5BB42BDEC163EBFE46 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bilal-small-project'
          slot-name: 'Production'
          package: .
